import { useEffect, useState } from "react";
import { format } from "date-fns";
import {
  Download,
  FileText,
  DollarSign,
  TrendingUp,
  TrendingDown,
} from "lucide-react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as ExcelJS from "exceljs";
import { saveAs } from "file-saver";

function Report() {
  const [transactions, setTransactions] = useState([]);
  const [accountInfo, setAccountInfo] = useState({
    address: "0x71C7...a51B",
    totalBalance: 50834.22,
    totalIncome: 12000.0,
    totalExpenses: 7185.78,
  });

  useEffect(() => {
    // Sample data - in production, fetch from API or context
    const sampleTransactions = [
      {
        id: "tx1",
        type: "receive",
        amount: 2500.0,
        description: "Salary Deposit",
        date: new Date(),
      },
      {
        id: "tx2",
        type: "send",
        amount: -120.5,
        description: "Netflix Subscription",
        date: new Date(),
      },
      {
        id: "tx3",
        type: "receive",
        amount: 800.0,
        description: "Freelance Payment",
        date: new Date(2025, 11, 20),
      },
      {
        id: "tx4",
        type: "send",
        amount: -45.0,
        description: "Coffee Shop",
        date: new Date(2025, 11, 19),
      },
      {
        id: "tx5",
        type: "receive",
        amount: 1500.0,
        description: "Project Bonus",
        date: new Date(2025, 11, 15),
      },
      {
        id: "tx6",
        type: "send",
        amount: -200.0,
        description: "Grocery Shopping",
        date: new Date(2025, 11, 10),
      },
    ];
    setTransactions(sampleTransactions);
  }, []);

  const generatePDF = () => {
    const doc = new jsPDF("p", "mm", "a4");
    const pageWidth = doc.internal.pageSize.getWidth();

    // Title
    doc.setFontSize(20);
    doc.text("Wallet Transaction Report", pageWidth / 2, 20, {
      align: "center",
    });

    // Report Date
    doc.setFontSize(12);
    doc.text(
      `Generated on: ${format(new Date(), "MMMM d, yyyy")}`,
      pageWidth / 2,
      30,
      { align: "center" }
    );

    // Account Information
    doc.setFontSize(14);
    doc.text("Account Information", 14, 45);
    doc.setFontSize(11);
    doc.text(`Wallet Address: ${accountInfo.address}`, 14, 55);
    doc.text(
      `Total Balance: $${accountInfo.totalBalance.toLocaleString()}`,
      14,
      63
    );
    doc.text(
      `Total Income: $${accountInfo.totalIncome.toLocaleString()}`,
      14,
      71
    );
    doc.text(
      `Total Expenses: $${accountInfo.totalExpenses.toLocaleString()}`,
      14,
      79
    );
    doc.text(
      `Net Cash Flow: $${(
        accountInfo.totalIncome - accountInfo.totalExpenses
      ).toLocaleString()}`,
      14,
      87
    );

    // Transactions Table
    doc.setFontSize(14);
    doc.text("Transaction History", 14, 105);

    const tableData = transactions.map((tx) => [
      format(tx.date, "MMM d, yyyy"),
      tx.description,
      tx.type === "receive" ? "Income" : "Expense",
      tx.amount > 0
        ? `+$${tx.amount.toFixed(2)}`
        : `-$${Math.abs(tx.amount).toFixed(2)}`,
    ]);

    // Changed to call autoTable as a function
    autoTable(doc, {
      head: [["Date", "Description", "Type", "Amount"]],
      body: tableData,
      startY: 115,
      theme: "striped",
      headStyles: { fillColor: [37, 99, 235] },
      styles: { fontSize: 10 },
    });

    // Footer
    const finalY = doc.lastAutoTable.finalY || 115;
    doc.setFontSize(10);
    doc.text(
      "Report generated by LTRansact Wallet",
      pageWidth / 2,
      finalY + 20,
      { align: "center" }
    );

    doc.save(`LTRansact_Report_${format(new Date(), "yyyy-MM-dd")}.pdf`);
  };

  const generateExcel = async () => {
    const workbook = new ExcelJS.Workbook();
    workbook.creator = "LTRansact Wallet";
    workbook.created = new Date();

    // Summary Sheet
    const summarySheet = workbook.addWorksheet("Summary");
    summarySheet.addRow(["Wallet Report Summary"]);
    summarySheet.addRow(["Generated on", format(new Date(), "MMMM d, yyyy")]);
    summarySheet.addRow([]);
    summarySheet.addRow(["Account Information"]);
    summarySheet.addRow(["Wallet Address", accountInfo.address]);
    summarySheet.addRow([
      "Total Balance",
      `$${accountInfo.totalBalance.toLocaleString()}`,
    ]);
    // Add more rows as needed...

    // Transactions Sheet
    const transSheet = workbook.addWorksheet("Transactions");
    transSheet.addRow(["Date", "Description", "Type", "Amount"]);
    transactions.forEach((tx) => {
      transSheet.addRow([
        format(tx.date, "yyyy-MM-dd"),
        tx.description,
        tx.type === "receive" ? "Income" : "Expense",
        tx.amount,
      ]);
    });

    const buffer = await workbook.xlsx.writeBuffer();
    const blob = new Blob([buffer], { type: "application/octet-stream" });
    saveAs(blob, `LTRansact_Report_${format(new Date(), "yyyy-MM-dd")}.xlsx`);
  };

  const totalIncome = transactions
    .filter((t) => t.type === "receive")
    .reduce((sum, t) => sum + t.amount, 0);
  const totalExpenses = transactions
    .filter((t) => t.type === "send")
    .reduce((sum, t) => sum + Math.abs(t.amount), 0);

  return (
    <div className="min-h-screen bg-gray-50 p-6">
      {/* Header */}
      <div className="mb-8 flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-gray-800">Reports</h1>
          <p className="text-gray-600 mt-2">
            Generate and download detailed reports of your wallet activity
          </p>
        </div>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
        <div className="bg-white rounded-2xl shadow-sm border border-gray-200 p-6">
          <div className="flex items-center justify-between mb-4">
            <div className="p-3 bg-blue-100 rounded-lg">
              <DollarSign size={28} className="text-blue-600" />
            </div>
          </div>
          <p className="text-gray-600 text-sm">Total Balance</p>
          <p className="text-2xl font-bold mt-2">
            ${accountInfo.totalBalance.toLocaleString()}
          </p>
        </div>

        <div className="bg-white rounded-2xl shadow-sm border border-gray-200 p-6">
          <div className="flex items-center justify-between mb-4">
            <div className="p-3 bg-green-100 rounded-lg">
              <TrendingUp size={28} className="text-green-600" />
            </div>
          </div>
          <p className="text-gray-600 text-sm">Total Income</p>
          <p className="text-2xl font-bold mt-2 text-green-600">
            +${totalIncome.toLocaleString()}
          </p>
        </div>

        <div className="bg-white rounded-2xl shadow-sm border border-gray-200 p-6">
          <div className="flex items-center justify-between mb-4">
            <div className="p-3 bg-red-100 rounded-lg">
              <TrendingDown size={28} className="text-red-600" />
            </div>
          </div>
          <p className="text-gray-600 text-sm">Total Expenses</p>
          <p className="text-2xl font-bold mt-2 text-red-600">
            -${totalExpenses.toLocaleString()}
          </p>
        </div>

        <div className="bg-white rounded-2xl shadow-sm border border-gray-200 p-6">
          <div className="flex items-center justify-between mb-4">
            <div className="p-3 bg-purple-100 rounded-lg">
              <FileText size={28} className="text-purple-600" />
            </div>
          </div>
          <p className="text-gray-600 text-sm">Transactions</p>
          <p className="text-2xl font-bold mt-2">{transactions.length}</p>
        </div>
      </div>

      {/* Export Buttons */}
      <div className="bg-white rounded-2xl shadow-sm border border-gray-200 p-8 mb-8 text-center">
        <h2 className="text-2xl font-semibold text-gray-800 mb-4">
          Download Your Report
        </h2>
        <p className="text-gray-600 mb-8 max-w-2xl mx-auto">
          Export your complete wallet report including account details, balance
          summary, and full transaction history.
        </p>

        <div className="flex flex-col sm:flex-row items-center justify-center gap-6">
          <button
            onClick={generatePDF}
            className="flex items-center gap-3 px-8 py-4 bg-red-600 hover:bg-red-700 text-white font-medium rounded-xl shadow-lg transition transform hover:scale-105 cursor-pointer"
          >
            <Download size={24} />
            Download as PDF
          </button>

          <button
            onClick={generateExcel}
            className="flex items-center gap-3 px-8 py-4 bg-green-600 hover:bg-green-700 text-white font-medium rounded-xl shadow-lg transition transform hover:scale-105 cursor-pointer"
          >
            <Download size={24} />
            Download as Excel
          </button>
        </div>
      </div>

      {/* Preview Note */}
      <div className="text-center text-gray-500 text-sm">
        <p>
          Reports are generated based on current wallet data as of{" "}
          {format(new Date(), "MMMM d, yyyy")}
        </p>
      </div>
    </div>
  );
}

export default Report;
